# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoSport' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoSport

pod 'Firebase/Core'
pod 'Firebase/Auth'

  target 'CoSportUnitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
